name: Test application running state
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    name: Test with Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Try an execution
      run: |        
        python tls_cert_discovery.py -r 217.31.74.128/28 -o test.xlsx
        ls -l test.xlsx
